export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO_FORM = 'TOGGLE_TODO_FORM';
export const SET_ACTIVE_TODO_EDITING = 'SET_ACTIVE_TODO_EDITING';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const SET_TODO_FILTERS = 'SET_TODO_FILTERS';
