export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO_FORM = 'TOGGLE_TODO_FORM';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const SET_ACTIVE_TODO_EDITING = 'SET_ACTIVE_TODO_EDITING';
